# Generated by Django 3.0.5 on 2021-01-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20200717_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(max_length=5000, verbose_name='Text'),
        ),
    ]
