# Generated by Django 3.0.5 on 2021-01-26 13:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='caption',
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Text'),
        ),
    ]
