# Generated by Django 3.0.5 on 2021-01-26 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20210126_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='caption',
        ),
    ]
