# Generated by Django 3.0.5 on 2021-01-24 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0004_auto_20200814_0659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
