# Generated by Django 3.0.5 on 2021-01-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0005_auto_20210124_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.IntegerField(blank=True, default=91, null=True),
        ),
    ]
