# Generated by Django 3.0.5 on 2021-01-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0007_auto_20210124_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.URLField(blank=True, default='www.facebook.com', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True, default='www.github.com', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.URLField(blank=True, default='www.instagram.com', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.URLField(blank=True, default='www.twitter.com', null=True),
        ),
    ]
