# Generated by Django 3.0.5 on 2021-01-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0008_auto_20210124_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
